/*****************************************************************************
* Product: Buzzer module interface for ECEG347 pulse rate monitor and
* 		   microwave (buzzer.h)
*
* Version: 0.2
* Updated: Mar 13, 2017
*
* Authors: Philip Asare
*
* Copyright (C) 2017 Philip Asare and <insert your name here>.
* All rights reserved.
*
*
* Contacts:
* 			Philip Asare (pkda001@bucknell.edu)
*****************************************************************************/

#ifndef DOOR_DOOR_H_
#define DOOR_DOOR_H_

#include <stdint.h>
#include <stdbool.h>

extern uint_fast8_t DoorSensor_port;
extern uint_fast16_t DoorSensor_pin;

uint32_t DoorSensor_interrupt;

/* Intialize door */
void DoorSensor_setup(void);

/* Check if door is open (or closed) */
bool DoorSensor_isOpen(void);

/* Handle the interrupt generated by opening or closing the door. */
void DoorSensor_handleInterrupt(void);

/* Report if door just opened
 *  NOTE: Must be implemented by the application
 */
void DoorSensor_reportDoorOpened(void);

#endif /* DOOR_DOOR_H_ */
